name: Update Catalog for polar.sh

on:
  workflow_dispatch:
  schedule:
  # On Fridays
  - cron: '0 12 * * 5'

env:
  FORCE_COLOR: "1"
  # renovate: datasource=pypi depName=uv
  UV_VERSION: 0.9.11

jobs:
  update_openapi_specification:
    name: Update Catalog
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    steps:
    - uses: actions/create-github-app-token@7e473efe3cb98aa54f8d4bac15400b15fad77d94 # v2.2.0
      id: generate-token
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
    - uses: astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244 # v7.1.4
      with:
        version: ${{ env.UV_VERSION }}
    - run: uv run scripts/update_openapi.py
    - id: check_snapshot_changes
      continue-on-error: true
      run: git diff --quiet tests/__snapshots__
    - uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
      if: steps.check_snapshot_changes.outcome == 'failure'
      with:
        title: 'fix: Update catalog'
        token: ${{ steps.generate-token.outputs.token }}
        signoff: true
